version: '3'
services:
  rabbit_go:
    image: go
    build: .
    container_name: go_client1
    entrypoint: bash
    tty: true
    stdin_open: true
    volumes:
      - .:/go/src/rabbit_client
    networks:
      - rabbit
    depends_on:
      - rabbitmq1

  rabbitmq1:
    container_name: rabbit1
    build: ./rabbitmq/
    environment:
     - RABBITMQ_DEFAULT_USER=user
     - RABBITMQ_DEFAULT_PASS=password
    ports:
     - "5672:5672"
     - "15672:15672"
    networks:
      - rabbit

networks:
  rabbit:
    driver: bridge